<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HomePage</title>
    <link rel="stylesheet" href="style.css">

</head>

<body class="home">
    <header>
       
    <nav>
        <span id="VASF">VASF Bank</span>
        <a href="contactus.html"><div id="hm">
            <img src="images/contact.png" alt="" width="25">
            <br><span id="hp">Contact</span>
            </div>
        </a>
        <a href="about.html"><div id="hm">
            <img src="images/abt.png" alt="" width="25">
            <br><span id="hp">About</span>
        </div></a>
        <a href="#"> <div id="hm">
            <img src="images/Home.png" alt="" width="25">
            <br><span id="hp">Home</span>
        </div> </a>

   </nav>
    </header>
    <hr color="yellow" style="height: 5px;margin-top: 0%;" >
    <main>
        <div id="wel">
        <span id="welcome" ><em>Welcome to VASF Bank</em></span>
        <br><br>
        <span id="subline">A tradition of trust</apan>
        </div>

        <a href="custtable.php"><div id="option1">
            
            <img src="images/Untitled design (6).png" alt="" width="100" >
            <br><span id="text3">View all Customers</span>
            
        </div></a>
        
        <a href="transfermoney.php"><div id="option2">
            
            <img src="images/Untitled design (2).png" alt="" width="100" >
            <br><span id="text">Transfer Money</span>
            
        </div></a>

        <a href="transactionhistory.php"><div id="option3" style="display:ruby; align-items: center;">
            
            <img src="images/Untitled design (7).png" alt="" width="100">
            <br><span id="text3">Transaction History</span>
            
        </div></a>
    </main>
    <footer>
        <p id="foot">&copf; Vinu Abinayaa</p> 
    </footer>
</body>
</html>